"""PlatformIO pre-build script: remove Ableton Link's /24 subnet filter.

Upstream Ableton/link commit d466f42 (2026-03-05) deleted the hardcoded /24
subnet filter in UdpMessenger.hpp because it drops discovery messages from
peers outside the interface's /24 — which breaks link-local (169.254/16)
direct-cable sessions. The docwilco/esp_abl_link component still vendors the
pre-fix Link 3.1.5, and managed_components/ is regenerated by the component
manager, so this script re-applies the removal whenever the pristine file
reappears. Idempotent: does nothing once the filter is gone.
"""
import re
from pathlib import Path

Import("env")  # noqa: F821  (PlatformIO construct)

TARGET = Path(env["PROJECT_DIR"]) / (  # noqa: F821
    "managed_components/docwilco__esp_abl_link/vendor/ableton-link/"
    "include/ableton/discovery/UdpMessenger.hpp"
)

FILTER_RE = re.compile(
    r"[ \t]*// On Linux multicast messages.*?"
    r"if \(!ignoreIpV4Message\)\n[ \t]*\{\n(.*?)\n[ \t]*\}\n",
    re.DOTALL,
)


def dedent_body(body: str) -> str:
    return "\n".join(
        line[2:] if line.startswith("  ") else line for line in body.split("\n")
    )


if not TARGET.exists():
    print("link-patch: UdpMessenger.hpp not found (component not downloaded yet) — "
          "run the build again after the component manager fetches it")
elif "ignoreIpV4Message" not in TARGET.read_text(encoding="utf-8"):
    pass  # already patched
else:
    text = TARGET.read_text(encoding="utf-8")
    new_text, n = FILTER_RE.subn(lambda m: dedent_body(m.group(1)) + "\n", text)
    if n == 1 and "ignoreIpV4Message" not in new_text:
        TARGET.write_text(new_text, encoding="utf-8")
        print("link-patch: removed /24 subnet filter from UdpMessenger.hpp")
    else:
        raise SystemExit(
            "link-patch: UdpMessenger.hpp contains the subnet filter but the "
            "patch pattern did not match — the component version probably "
            "changed. Update patches/patch_link_subnet_filter.py or verify "
            "the new Link version already includes upstream commit d466f42."
        )
