[env:wt32-eth01]
platform  = espressif32
board     = wt32-eth01
framework = espidf

monitor_speed = 115200
upload_speed  = 115200

build_flags =
    -std=gnu++17
    -Wno-error=multichar
    -Wno-error=redundant-move
    -Wno-error=missing-field-initializers
    -Desp_netif_next=esp_netif_next_unsafe

build_unflags = -std=gnu++11

board_build.partitions = partitions.csv

extra_scripts = pre:patches/patch_link_subnet_filter.py

[env:native]
platform = native
build_flags = -std=c++17
test_build_src = false
